### PR TITLE
Add prettier and precommit hooks

### PR DESCRIPTION
**Pull request by sabeurthabti**

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://dev.quranicaudio.com:32813

**Comment by ahmedre** [comment]
Deployed to: http://dev.quranicaudio.com:32814

**Comment by mmahalwy** [comment]
Want to add it to quran.com?

**Comment by sabeurthabti** [comment]
@mmahalwy yes - inshallah tonight!

**Pull request merged**
