### PR TITLE
Allow play/pause/next/previous keyboard control and fix mobile audio player next/previous button disabling

### LINKED ISSUE #92: Allow keyboard to control audio playing
Add support for using the keyboard spacebar to play and pause audio. Skipping forward and backward through surahs can also be added using the left/up and right/bottom arrow keys. If the maintainers approve of this feature I am happy to add it.

### LINKED ISSUE #94: Mobile audio player enables previous button instead of next button
When playing Surat Al-Fatihah in the mobile audio player, the button to play the previous surah is enabled while the button to play the next surah is disabled. It should be the other way around. Clicking the previous button in this case throws an error since it tries to load the source as ".../000.mp3".

screen shot 2017-10-28 at 12 27 42 am

### PR DESCRIPTION
**Pull request by mmmoussa**
In both the desktop and mobile audio players added the ability to:
- play/pause using the spacebar
- skip to the next surah using the right or down arrow keys
- skip to the previous surah using the left or up arrow keys

Closes #92.

Also fixed the bug where the mobile audio player previous button would be disabled instead of the next button, and vice versa. Fixes #94.

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://dev.quranicaudio.com:32854

**Comment by mmahalwy** [comment]
@sabeurthabti

**Comment by ahmedre** [comment]
Deployed to: http://dev.quranicaudio.com:32856

**Comment by sabeurthabti** [comment]
@mmmoussa awesome work. Sorry for the delay in reviewing this. 
Approved!

**Pull request merged**
