### PR TITLE
Remove dead (or worse) links

### PR DESCRIPTION
**Pull request by mustafa0x**

### CODE REVIEW

**Comment by mustafa0x** [comment]
The repo should be searched for these domains; I found other links to these sites.

**Comment by mustafa0x** [comment]
Same for moments.net

**Comment by ahmedre** [comment]
some of these are in the database - will add a note to self to clean this up on the db level in sha' Allah - jazakAllah khair for the patch

**Comment by ahmedre** [comment]
rebuild

**Comment by ahmedre** [comment]
Deployed to: http://dev.quranicaudio.com:32782

**Pull request merged**
