### PR TITLE
Switch download to https

### PR DESCRIPTION
**Pull request by ahmedre**

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://dev.quranicaudio.com:32821

**Comment by ahmedre** [comment]
i am not too happy with the fact this url is repeated everywhere - i think something like `AUDIO_URL` defined in src/actions/audioplayer.js and used in src/reducers/audioplayer.js makes more sense - any suggestions?

**Comment by ahmedre** [comment]
also, i seem to recall something about not having the protocol within the url if i am not mistaken - i.e. something like //{url} so that it works automatically regardless of the protocol?

**Comment by sabeurthabti** [comment]
@ahmedre I will get round to ensure the URL isn't hardcoded everywhere.

**Pull request merged**
