### PR TITLE
wip on /download #56

### PR DESCRIPTION
**Pull request by sabeurthabti**
#56

### CODE REVIEW

**Comment by ahmedre** [comment]
Deployed to: http://dev.quranicaudio.com:32895

**Comment by ahmedre** [comment]
Deployed to: http://dev.quranicaudio.com:32896

**Comment by ahmedre** [comment]
Deployed to: http://dev.quranicaudio.com:32897

**Comment by ahmedre** [comment]
Deployed to: http://dev.quranicaudio.com:32901

**Comment by sabeurthabti** [comment]
screen shot 2016-11-17 at 20 34 52

**Comment by sabeurthabti** [comment]
closes #56

**Comment by sabeurthabti** [comment]
[](url)

**Comment by ahmedre** [comment]
Deployed to: http://dev.quranicaudio.com:32905

**Comment by ahmedre** [comment]
Deployed to: http://dev.quranicaudio.com:32906

**Comment by ahmedre** [comment]
Deployed to: http://dev.quranicaudio.com:32907

**Comment by ahmedre** [comment]
Deployed to: http://dev.quranicaudio.com:32908

**Pull request merged**
